import { Platform, StyleSheet } from 'react-native';

import { palette } from '@/constants/premium-theme';

const loginCardShadow = Platform.select({
  web: { boxShadow: '0px 18px 40px rgba(15, 23, 42, 0.12)' },
  default: { shadowColor: '#0f172a', shadowOpacity: 0.12, shadowRadius: 24, shadowOffset: { width: 0, height: 12 }, elevation: 4 },
});

const clientPetCardActiveShadow = Platform.select({
  web: { boxShadow: '0px 16px 34px rgba(255, 107, 53, 0.16)' },
  default: { shadowColor: '#ff6b35', shadowOpacity: 0.16, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 3 },
});

const cardShadow = Platform.select({
  web: { boxShadow: '0px 18px 36px rgba(15, 23, 42, 0.08)' },
  default: { shadowColor: '#0f172a', shadowOpacity: 0.08, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 2 },
});

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f8fafc' },
  pressFeedback: { opacity: 0.68, transform: [{ scale: 0.98 }] },
  keyboardArea: { flex: 1 },
  content: { paddingHorizontal: 18, paddingVertical: 18, gap: 18, alignItems: 'center' },
  appShell: { width: '100%', gap: 18 },
  authContent: { flexGrow: 1, justifyContent: 'center' },
  authStack: { width: '100%', maxWidth: 520, alignSelf: 'center', gap: 18, justifyContent: 'center' },
  authNotice: { width: '100%', borderRadius: 16, padding: 14, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', flexDirection: 'row', gap: 10 },
  loginShell: { position: 'relative', minHeight: '100%', width: '100%', maxWidth: 520, justifyContent: 'center', alignSelf: 'center', paddingVertical: 24 },
  loginLayout: { gap: 18 },
  loginLayoutWide: { flexDirection: 'row', alignItems: 'stretch' },
  loginBackdrop: { ...StyleSheet.absoluteFillObject, overflow: 'hidden' },
  loginAccentPrimary: { position: 'absolute', top: -40, right: -20, width: 220, height: 220, borderRadius: 999, backgroundColor: '#fed7aa', opacity: 0.6 },
  loginAccentSecondary: { position: 'absolute', bottom: 20, left: -50, width: 240, height: 240, borderRadius: 999, backgroundColor: '#ffedd5', opacity: 0.9 },
  loginCard: { width: '100%', borderRadius: 30, padding: 22, backgroundColor: 'rgba(255, 255, 255, 0.97)', borderWidth: 1, borderColor: '#e5e7eb', gap: 16, ...loginCardShadow },
  loginCardWide: { width: '100%', minWidth: 360, justifyContent: 'center' },
  loginEyebrow: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.4 },
  loginTitle: { color: palette.ink, fontSize: 32, lineHeight: 36, fontWeight: '800' },
  loginSubtitle: { color: palette.body, fontSize: 14, lineHeight: 22 },
  authModeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  authLink: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 999, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa' },
  authLinkActive: { backgroundColor: palette.clay, borderColor: palette.clay },
  authLinkText: { color: palette.body, fontSize: 12, fontWeight: '700' },
  authLinkTextActive: { color: palette.paper },
  loginFieldGroup: { gap: 10 },
  demoAccountRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  demoAccountChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa' },
  demoAccountChipText: { color: palette.clayDeep, fontSize: 12, fontWeight: '700' },
  clientHomeStack: { width: '100%', gap: 14 },
  clientHomeHero: { width: '100%', borderRadius: 30, padding: 20, backgroundColor: palette.clay, borderWidth: 1, borderColor: '#f59b72', gap: 16, ...Platform.select({ web: { boxShadow: '0px 20px 40px rgba(201, 74, 34, 0.28)' }, default: { shadowColor: '#c94a22', shadowOpacity: 0.28, shadowRadius: 24, shadowOffset: { width: 0, height: 14 }, elevation: 7 } }) },
  clientHomeHeroWide: {},
  clientHomeHeroCompact: { padding: 16, gap: 12 },
  clientHomeHeroTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 14 },
  clientHomeHeroCopy: { flex: 1, gap: 10 },
  clientHomeHeroActions: { flexDirection: 'row', gap: 8 },
  clientHomeHeroIconButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,255,255,0.18)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  clientHomeEyebrow: { color: 'rgba(255,255,255,0.86)', fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.2 },
  clientHomeTitle: { color: '#ffffff', fontSize: 31, lineHeight: 35, fontWeight: '800' },
  clientHomeTitleCompact: { fontSize: 27, lineHeight: 31 },
  clientHomeText: { color: 'rgba(255,255,255,0.88)', fontSize: 14, lineHeight: 22 },
  clientHomeTextCompact: { fontSize: 13, lineHeight: 20 },
  clientHomeHeroStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  clientHomeHeroStatCard: { flex: 1, minWidth: 96, borderRadius: 18, padding: 14, backgroundColor: 'rgba(255,255,255,0.14)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', gap: 6 },
  clientHomeHeroStatCardCompact: { padding: 10, minWidth: 88 },
  clientHomeHeroStatLabel: { color: 'rgba(255,255,255,0.82)', fontSize: 11, fontWeight: '700' },
  clientHomeHeroStatValue: { color: '#ffffff', fontSize: 24, fontWeight: '800' },
  clientHomeHeroStatValueCompact: { fontSize: 20 },
  clientWorkspaceRowInline: { width: '100%', gap: 8, padding: 14, borderRadius: 18, backgroundColor: '#fff8f1', borderWidth: 1, borderColor: '#ead7c6' },
  clientWorkspaceLabel: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  clientBottomNavWrap: { position: 'absolute', left: 0, right: 0, bottom: 0, alignItems: 'center' },
  clientBottomNav: { width: '100%', maxWidth: 420, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.96)', borderWidth: 1, borderColor: '#e5e7eb', ...Platform.select({ web: { boxShadow: '0px 12px 26px rgba(15, 23, 42, 0.12)' }, default: { shadowColor: '#0f172a', shadowOpacity: 0.1, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 6 } }) },
  clientTab: { flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 4, borderRadius: 16 },
  clientTabCompact: { minHeight: 46, paddingVertical: 0 },
  clientTabRoomy: { minHeight: 58, gap: 6 },
  clientTabActive: {},
  clientTabIconBubble: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8fafc' },
  clientTabIconBubbleCompact: { width: 38, height: 38, borderRadius: 19 },
  clientTabIconBubbleRoomy: { width: 38, height: 38, borderRadius: 19 },
  clientTabIconBubbleActive: { backgroundColor: palette.clay },
  clientTabText: { color: palette.body, fontSize: 11, fontWeight: '700', textAlign: 'center' },
  clientTabTextRoomy: { fontSize: 12 },
  clientTabTextActive: { color: palette.clayDeep },
  adminBottomNavWrap: { position: 'absolute', left: 0, right: 0, bottom: 0, alignItems: 'center' },
  adminBottomNav: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 8, paddingVertical: 8, borderRadius: 24, backgroundColor: 'rgba(255,255,255,0.98)', borderWidth: 1, borderColor: '#e5e7eb', ...Platform.select({ web: { boxShadow: '0px 14px 30px rgba(15, 23, 42, 0.14)' }, default: { shadowColor: '#0f172a', shadowOpacity: 0.12, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 7 } }) },
  adminBottomTab: { flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 4 },
  adminBottomTabCompact: { minHeight: 46, paddingVertical: 0 },
  adminBottomTabRoomy: { minHeight: 60, gap: 6 },
  adminBottomTabIconBubble: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8fafc' },
  adminBottomTabIconBubbleCompact: { width: 38, height: 38, borderRadius: 19 },
  adminBottomTabIconBubbleRoomy: { width: 38, height: 38, borderRadius: 19 },
  adminBottomTabIconBubbleActive: { backgroundColor: palette.clay },
  adminBottomTabText: { color: '#64748b', fontSize: 10, fontWeight: '700', textAlign: 'center' },
  adminBottomTabTextRoomy: { fontSize: 12 },
  adminBottomTabTextActive: { color: palette.clayDeep },
  clientSectionLabel: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1, marginTop: 2 },
  clientSectionIntro: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  clientSectionStat: { flex: 1, minWidth: 140, borderRadius: 18, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 4 },
  clientSectionStatValue: { color: palette.ink, fontSize: 22, fontWeight: '800', textTransform: 'capitalize' },
  clientSectionStatLabel: { color: palette.body, fontSize: 12, lineHeight: 18 },
  clientAdoptScreen: { width: '100%', gap: 14 },
  adminPetDirectoryScreen: { width: '100%', maxWidth: 520, alignSelf: 'center', gap: 14 },
  adminPetDirectoryHeader: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 12 },
  adminPetDirectoryHeaderCopy: { flex: 1, gap: 2 },
  adminPetDirectoryTitle: { color: palette.ink, fontSize: 26, lineHeight: 30, fontWeight: '800' },
  adminPetDirectorySubtitle: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminPetDirectoryActionButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', ...cardShadow },
  adminPetDirectorySearchRow: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminPetDirectorySearchBox: { flex: 1, minHeight: 46, borderRadius: 14, paddingHorizontal: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', flexDirection: 'row', alignItems: 'center', gap: 10, ...cardShadow },
  adminPetDirectorySearchInput: { flex: 1, color: palette.ink, fontSize: 13, paddingVertical: 0 },
  adminPetDirectoryFilterButton: { width: 46, height: 46, borderRadius: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center', ...cardShadow },
  adminPetDirectoryFilterButtonActive: { backgroundColor: '#fff7ed', borderColor: '#fed7aa' },
  adminPetDirectoryChipRow: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  adminPetDirectoryChip: { minHeight: 36, paddingHorizontal: 12, borderRadius: 18, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center' },
  adminPetDirectoryChipActive: { backgroundColor: palette.clay, borderColor: palette.clay },
  adminPetDirectoryChipText: { color: palette.body, fontSize: 12, fontWeight: '800' },
  adminPetDirectoryChipTextActive: { color: '#ffffff' },
  adminPetDirectoryList: { width: '100%', gap: 10 },
  adminPetDirectoryItem: { width: '100%', borderRadius: 22, padding: 12, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', flexDirection: 'row', alignItems: 'center', gap: 12, ...cardShadow },
  adminPetDirectoryItemActive: { backgroundColor: '#fff7ed', borderColor: '#fdba74' },
  adminPetDirectoryThumb: { width: 68, height: 68, borderRadius: 18, alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' },
  adminPetDirectoryThumbImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  adminPetDirectoryThumbGlow: { position: 'absolute', width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(255,255,255,0.45)' },
  adminPetDirectoryItemCopy: { flex: 1, gap: 3 },
  adminPetDirectoryItemName: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminPetDirectoryItemBreed: { color: palette.body, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  adminPetDirectoryItemMeta: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminPetDirectoryStatusPill: { marginTop: 2, alignSelf: 'flex-start', minHeight: 22, paddingHorizontal: 10, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  adminPetDirectoryStatusAvailable: { backgroundColor: '#fff1eb' },
  adminPetDirectoryStatusPending: { backgroundColor: '#ffedd5' },
  adminPetDirectoryStatusFostered: { backgroundColor: '#fff7ed' },
  adminPetDirectoryStatusAlert: { backgroundColor: '#fee2e2' },
  adminPetDirectoryStatusText: { color: palette.clayDeep, fontSize: 11, fontWeight: '800' },
  adminPetDirectoryEmptyState: { width: '100%', borderRadius: 20, padding: 16, backgroundColor: '#fff8f1', borderWidth: 1, borderColor: '#fed7aa', gap: 6 },
  adminPetEditorCard: { width: '100%', borderRadius: 24, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 12, ...cardShadow },
  adminPetEditorHeader: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  adminPetEditorTitle: { color: palette.ink, fontSize: 22, fontWeight: '800' },
  adminPetEditorText: { color: palette.body, fontSize: 12, lineHeight: 18, marginTop: 4 },
  adminPetEditorResetButton: { minHeight: 34, paddingHorizontal: 14, borderRadius: 12, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center' },
  adminPetEditorResetButtonText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  clientAdoptFilterBar: { width: '100%', gap: 10 },
  clientAdoptFilterChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  clientAdoptFilterChip: { minHeight: 44, paddingHorizontal: 18, borderRadius: 22, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center' },
  clientAdoptFilterChipActive: { backgroundColor: '#fff1eb', borderColor: '#fdba74' },
  clientAdoptFilterChipText: { color: palette.body, fontSize: 13, fontWeight: '800' },
  clientAdoptFilterChipTextActive: { color: palette.clayDeep },
  clientAdoptResultsCard: { width: '100%', borderRadius: 24, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 16, ...cardShadow },
  clientAdoptResultsHeader: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  clientAdoptResultsTitle: { color: palette.ink, fontSize: 24, fontWeight: '800', marginTop: 3 },
  clientAdoptResultsText: { color: palette.body, fontSize: 13, lineHeight: 20, marginTop: 6, maxWidth: 520 },
  clientAdoptResultsAction: { minHeight: 40, paddingHorizontal: 14, borderRadius: 14, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center' },
  clientAdoptResultsActionText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  clientAdoptResultsList: { width: '100%', gap: 14 },
  clientAdoptResultsListGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  clientAdoptEmptyState: { width: '100%', borderRadius: 20, padding: 16, backgroundColor: '#fff8f1', borderWidth: 1, borderColor: '#fed7aa', gap: 6 },
  clientAdoptSpotlightCard: { width: '100%', borderRadius: 24, padding: 16, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#fdba74', gap: 14, ...cardShadow },
  clientAdoptSpotlightHeader: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  clientAdoptSpotlightCopy: { flex: 1, minWidth: 220, gap: 4 },
  clientAdoptSpotlightTitle: { color: palette.ink, fontSize: 24, fontWeight: '800' },
  clientAdoptSpotlightText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  clientAdoptSpotlightFacts: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  clientAdoptSpotlightFact: { flex: 1, minWidth: 110, borderRadius: 18, padding: 13, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fde3c2', gap: 4 },
  clientAdoptSpotlightFactLabel: { color: palette.clay, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  clientAdoptSpotlightFactValue: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  clientDonateScreen: { width: '100%', maxWidth: 560, alignSelf: 'center', gap: 14 },
  clientDonateTopBar: { width: '100%', minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  clientDonateBackButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e7edf3', alignItems: 'center', justifyContent: 'center' },
  clientDonateBackButtonMuted: { opacity: 0.28 },
  clientDonateBackButtonSpacer: { width: 38, height: 38 },
  clientDonateTopTitle: { flex: 1, color: palette.ink, fontSize: 17, fontWeight: '800', textAlign: 'center' },
  clientDonateTabRow: { width: '100%', flexDirection: 'row', gap: 8, padding: 4, borderRadius: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e7edf3' },
  clientDonateTab: { flex: 1, minHeight: 42, borderRadius: 12, backgroundColor: 'transparent', borderWidth: 1, borderColor: 'transparent', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  clientDonateTabActive: { backgroundColor: palette.clay, borderColor: palette.clay },
  clientDonateTabDisabled: { opacity: 0.58 },
  clientDonateStepDot: { width: 23, height: 23, borderRadius: 12, backgroundColor: '#f1f5f9', alignItems: 'center', justifyContent: 'center' },
  clientDonateStepDotActive: { backgroundColor: 'rgba(255,255,255,0.22)' },
  clientDonateStepDotDisabled: { backgroundColor: '#e2e8f0' },
  clientDonateStepDotText: { color: palette.body, fontSize: 11, fontWeight: '800' },
  clientDonateStepDotTextActive: { color: '#ffffff' },
  clientDonateTabText: { color: palette.body, fontSize: 13, fontWeight: '800' },
  clientDonateTabTextActive: { color: '#ffffff' },
  clientDonateCard: { width: '100%', borderRadius: 20, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e7edf3', gap: 14, ...Platform.select({ web: { boxShadow: '0px 10px 24px rgba(15, 23, 42, 0.045)' }, default: { shadowColor: '#0f172a', shadowOpacity: 0.045, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 1 } }) },
  clientDonateInfoCard: { alignSelf: 'stretch' },
  clientDonateCardHeader: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  clientDonateCardTitle: { color: palette.ink, fontSize: 17, lineHeight: 22, fontWeight: '800' },
  clientDonateLabel: { color: palette.clayDeep, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  clientDonateAccountRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  clientDonateAccountIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center' },
  clientDonateAccountCopy: { flex: 1, gap: 2 },
  clientDonateAccountName: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  clientDonateAccountMeta: { color: palette.body, fontSize: 12, lineHeight: 18 },
  clientDonateAnonymousChip: { minHeight: 34, paddingHorizontal: 12, borderRadius: 12, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e7edf3', alignItems: 'center', justifyContent: 'center' },
  clientDonateAnonymousChipActive: { backgroundColor: '#fff7ed', borderColor: '#fdba74' },
  clientDonateAnonymousChipText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  clientDonateAnonymousChipTextActive: { color: palette.clayDeep },
  clientDonateEditButton: { minHeight: 32, paddingHorizontal: 10, borderRadius: 12, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  clientDonateEditButtonText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  clientDonateRecipientCard: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 16, padding: 12, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#fed7aa' },
  clientDonateRecipientMedia: { width: 48, height: 48, borderRadius: 16, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center' },
  clientDonateRecipientCopy: { flex: 1, gap: 4 },
  clientDonateRecipientTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  clientDonateRecipientBadge: { minHeight: 30, paddingHorizontal: 11, borderRadius: 12, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center' },
  clientDonateRecipientBadgeText: { color: palette.clayDeep, fontSize: 11, fontWeight: '800' },
  clientDonateCurrencyText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 12, backgroundColor: '#fff7ed', overflow: 'hidden' },
  clientDonateQuickAmountRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  clientDonateQuickAmount: { flexGrow: 1, minHeight: 40, paddingHorizontal: 13, borderRadius: 12, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', alignItems: 'center', justifyContent: 'center' },
  clientDonateQuickAmountActive: { backgroundColor: palette.clay, borderColor: palette.clay },
  clientDonateQuickAmountText: { color: palette.body, fontSize: 12, fontWeight: '800' },
  clientDonateQuickAmountTextActive: { color: '#ffffff' },
  clientDonateAmountWrap: { minHeight: 60, borderRadius: 16, borderWidth: 1, borderColor: '#e2e8f0', backgroundColor: '#ffffff', paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 10 },
  clientDonateAmountPrefix: { color: palette.clayDeep, fontSize: 13, fontWeight: '800' },
  clientDonateAmountInput: { flex: 1, color: palette.ink, fontSize: 28, fontWeight: '800', paddingVertical: 0 },
  clientDonateAmountSuffix: { color: palette.body, fontSize: 13, fontWeight: '700' },
  clientDonateNotice: { width: '100%', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: '#fffbeb', borderWidth: 1, borderColor: '#fde68a', flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  clientDonateNoticeText: { flex: 1, color: '#92400e', fontSize: 12, lineHeight: 18, fontWeight: '700' },
  clientDonateInlineError: { color: palette.danger, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  clientDonatePaymentMethodGrid: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  clientDonatePaymentOption: { flexGrow: 1, minWidth: 124, minHeight: 48, borderRadius: 6, paddingHorizontal: 10, paddingVertical: 8, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#d9e0e8', flexDirection: 'row', alignItems: 'center', gap: 7 },
  clientDonatePaymentOptionActive: { borderColor: '#fdba74', backgroundColor: '#fffaf5' },
  clientDonatePaymentOptionCopy: { flex: 1, minWidth: 0 },
  clientDonatePaymentOptionTitle: { color: palette.ink, fontSize: 13, fontWeight: '800' },
  clientDonatePaymentOptionText: { color: palette.body, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  clientDonatePaymentRadio: { width: 14, height: 14, borderRadius: 7, borderWidth: 1.5, borderColor: '#94a3b8', alignItems: 'center', justifyContent: 'center' },
  clientDonatePaymentRadioActive: { borderColor: palette.clay },
  clientDonatePaymentRadioDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: palette.clay },
  clientDonatePaymentDetailsBox: { width: '100%', borderRadius: 18, padding: 14, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e7edf3', gap: 12 },
  clientDonatePaymentDetailsHeader: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  clientDonatePaymentDetailsTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  clientDonatePaymentDetailsText: { color: palette.body, fontSize: 12, lineHeight: 18, fontWeight: '600', marginTop: 2 },
  clientDonatePaymentFieldGrid: { gap: 10 },
  clientDonateMethodLogoShell: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' },
  clientDonateMethodLogoShellCompact: { width: 24, height: 24, borderRadius: 7 },
  clientDonateMethodLogoShellLarge: { width: 50, height: 50, borderRadius: 16 },
  clientDonateMethodLogoShellAsset: { backgroundColor: '#ffffff', borderColor: '#dbeafe', padding: 4 },
  clientDonateMethodLogoShellAssetActive: { borderColor: '#93c5fd' },
  clientDonateMethodLogoAssetImage: { width: 36, height: 36, borderRadius: 12 },
  clientDonateMethodLogoAssetImageCompact: { width: 20, height: 20, borderRadius: 6 },
  clientDonateMethodLogoAssetImageLarge: { width: 42, height: 42, borderRadius: 14 },
  clientDonateFieldGrid: { gap: 10 },
  clientDonateFieldGridWide: { flexDirection: 'row', flexWrap: 'wrap' },
  clientDonateFieldItem: { width: '100%' },
  clientDonateActionRow: { width: '100%', gap: 10 },
  clientDonateSummaryCard: { width: '100%', borderRadius: 20, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e7edf3', gap: 14 },
  clientDonateSummaryList: { width: '100%', gap: 10 },
  clientDonateSummaryRow: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: '#eef2f6' },
  clientDonateSummaryLabel: { color: palette.body, fontSize: 12, fontWeight: '700' },
  clientDonateSummaryValue: { flex: 1, color: palette.ink, fontSize: 13, lineHeight: 18, fontWeight: '800', textAlign: 'right' },
  clientDonateTotalsCard: { width: '100%', borderRadius: 20, padding: 16, backgroundColor: palette.ink, borderWidth: 1, borderColor: '#334155', flexDirection: 'row', alignItems: 'center', gap: 12 },
  clientDonateTotalSummaryIcon: { width: 44, height: 44, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', alignItems: 'center', justifyContent: 'center' },
  clientDonateTotalRow: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  clientDonateTotalCopy: { flex: 1, gap: 3 },
  clientDonateTotalLabel: { color: '#cbd5e1', fontSize: 13, lineHeight: 18 },
  clientDonateTotalValue: { color: palette.ink, fontSize: 14, fontWeight: '700' },
  clientDonateDivider: { height: 1, backgroundColor: '#e5e7eb', marginVertical: 2 },
  clientDonateGrandLabel: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  clientDonateGrandValue: { color: '#ffffff', fontSize: 20, fontWeight: '800' },
  clientHomeFilterBar: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10 },
  clientHomeFilterBarCompact: { gap: 8 },
  clientHomeFilterChip: { minHeight: 42, paddingHorizontal: 18, borderRadius: 21, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center' },
  clientHomeFilterChipActive: { backgroundColor: palette.clay, borderColor: palette.clay },
  clientHomeFilterChipText: { color: palette.body, fontSize: 13, fontWeight: '800' },
  clientHomeFilterChipTextActive: { color: '#ffffff' },
  clientHomeBrowseSection: { width: '100%', borderRadius: 24, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 14, ...cardShadow },
  clientHomeBrowseSectionCompact: { padding: 12, gap: 10 },
  clientHomeSectionHeader: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  clientHomeSectionText: { color: palette.body, fontSize: 13, lineHeight: 19, marginTop: 4 },
  clientHomeInlineAction: { minHeight: 44, paddingHorizontal: 16, borderRadius: 14, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-start' },
  clientHomeInlineActionText: { color: palette.clayDeep, fontSize: 13, fontWeight: '800' },
  clientHomeSingleCardWrap: { width: '100%' },
  clientHomeSupportGrid: { width: '100%', gap: 14 },
  clientHomeSupportGridWide: { flexDirection: 'row', alignItems: 'stretch' },
  clientHomeSidePanel: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 12, ...cardShadow },
  clientQuickActionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  clientQuickActionCard: { flexGrow: 1, flexBasis: 180, minWidth: 180, borderRadius: 18, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 8 },
  clientQuickActionIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff7ed' },
  clientQuickActionTitle: { color: palette.ink, fontSize: 15, fontWeight: '800' },
  clientQuickActionText: { color: palette.body, fontSize: 12, lineHeight: 19 },
  clientHomeChecklist: { gap: 12 },
  clientHomeChecklistItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  clientHomeChecklistBadge: { width: 28, height: 28, borderRadius: 14, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  clientHomeChecklistBadgeText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  clientHomeChecklistCopy: { flex: 1, gap: 3 },
  clientHomeChecklistTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  clientHomeChecklistText: { color: palette.body, fontSize: 12, lineHeight: 19 },
  clientPetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  clientPetRail: { paddingVertical: 4, paddingRight: 6 },
  clientPetCard: { width: 190, marginRight: 12, borderRadius: 24, overflow: 'hidden', backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 0, ...cardShadow },
  clientPetCardActive: { borderColor: '#fdba74', backgroundColor: '#fff7ed', ...clientPetCardActiveShadow },
  clientPetMedia: { minHeight: 170, backgroundColor: palette.clay, justifyContent: 'center', position: 'relative', overflow: 'hidden' },
  clientPetMediaImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%', backgroundColor: '#f8fafc' },
  clientPetMediaScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15, 23, 42, 0.18)' },
  clientPetMediaHome: { minHeight: 156 },
  clientPetMediaAdopt: { minHeight: 212 },
  clientPetMediaTop: { position: 'absolute', top: 12, left: 12, right: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, zIndex: 2 },
  clientPetMediaBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: 'rgba(15,23,42,0.54)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.22)' },
  clientPetMediaBadgeText: { color: '#ffffff', fontSize: 11, fontWeight: '800' },
  clientPetFavoriteButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#ffffff', alignItems: 'center', justifyContent: 'center' },
  clientPetFavoriteButtonActive: { backgroundColor: palette.clay },
  clientPetMediaCenter: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', zIndex: 1 },
  clientPetMediaIconWrap: { width: 86, height: 86, borderRadius: 43, backgroundColor: 'rgba(255,255,255,0.14)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)' },
  clientPetMediaIconWrapHome: { width: 88, height: 88, borderRadius: 44 },
  clientPetMediaIconWrapAdopt: { width: 112, height: 112, borderRadius: 56, backgroundColor: 'rgba(255,255,255,0.16)' },
  clientPetCardBody: { padding: 14, gap: 8 },
  clientPetCardBodyHome: { padding: 12, gap: 8 },
  clientPetCardBodyAdopt: { padding: 16, gap: 9 },
  clientPetName: { color: palette.ink, fontSize: 18, fontWeight: '800' },
  clientPetNameHome: { fontSize: 19, lineHeight: 23 },
  clientPetNameAdopt: { fontSize: 24, lineHeight: 28 },
  clientPetBreed: { color: palette.body, fontSize: 13, lineHeight: 19 },
  clientPetBreedHome: { fontSize: 13, lineHeight: 18 },
  clientPetBreedAdopt: { fontSize: 14, lineHeight: 20 },
  clientPetLocation: { color: palette.body, fontSize: 12, lineHeight: 18 },
  clientPetMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  clientPetMeta: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: '#f8fafc', color: palette.body, fontSize: 12, fontWeight: '700' },
  clientPetSpotlight: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 12, ...cardShadow },
  clientPetSpotlightHeader: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  clientPetSpotlightIdentity: { flex: 1, minWidth: 180, gap: 4 },
  clientPetSpotlightBreed: { color: palette.body, fontSize: 14 },
  clientPetSpotlightBadge: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, backgroundColor: '#f3e1cf' },
  clientPetSpotlightBadgeText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  clientPetFacts: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  clientPetFact: { flex: 1, minWidth: 96, borderRadius: 16, padding: 12, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', gap: 4 },
  clientPetFactLabel: { color: palette.clay, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  clientPetFactValue: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  clientSpotlightLayout: { gap: 14 },
  clientSpotlightLayoutWide: { flexDirection: 'row', alignItems: 'flex-start' },
  clientPetSpotlightSummary: { flex: 1.05 },
  clientFormCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 10, ...cardShadow },
  clientFormCardWide: { flex: 0.95 },
  clientMethodGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  clientMethodCard: { flexBasis: '48%', flexGrow: 1, minWidth: 140, borderRadius: 18, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 6 },
  clientMethodCardActive: { backgroundColor: '#fff7ed', borderColor: '#fb923c' },
  clientMethodTitle: { color: palette.ink, fontSize: 14, fontWeight: '800', textTransform: 'capitalize' },
  clientMethodText: { color: palette.body, fontSize: 12, lineHeight: 18 },
  clientFormGrid: { gap: 10 },
  clientFormGridWide: { flexDirection: 'row', flexWrap: 'wrap' },
  clientFormGridItem: { width: '100%' },
  clientFormGridItemWide: { width: '100%' },
  clientSettingsScreen: { width: '100%', gap: 16 },
  clientSettingsHero: { width: '100%', borderRadius: 30, padding: 20, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 16, ...cardShadow },
  clientSettingsHeroTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 14 },
  clientSettingsHeaderCopy: { flex: 1, minWidth: 0, gap: 4 },
  clientSettingsEyebrow: { color: palette.clayDeep, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  clientSettingsTitle: { color: palette.ink, fontSize: 26, lineHeight: 31, fontWeight: '800' },
  clientSettingsSubtitle: { color: palette.body, fontSize: 13, lineHeight: 19 },
  clientSettingsHeaderBadge: { minHeight: 32, paddingHorizontal: 10, borderRadius: 12, backgroundColor: '#eefbf4', borderWidth: 1, borderColor: '#bbf7d0', flexDirection: 'row', alignItems: 'center', gap: 6 },
  clientSettingsHeaderBadgeText: { color: '#15803d', fontSize: 11, fontWeight: '800' },
  clientSettingsProfileRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  clientSettingsAvatar: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  clientSettingsAvatarImage: { width: '100%', height: '100%' },
  clientSettingsAvatarText: { color: palette.clayDeep, fontSize: 22, fontWeight: '800' },
  clientSettingsProfileCopy: { flex: 1, gap: 3 },
  clientSettingsProfileName: { color: palette.ink, fontSize: 20, fontWeight: '800' },
  clientSettingsProfileEmail: { color: palette.body, fontSize: 13, lineHeight: 18 },
  clientSettingsEditButton: { minHeight: 38, paddingHorizontal: 14, borderRadius: 12, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-start' },
  clientSettingsEditButtonText: { color: '#ffffff', fontSize: 13, fontWeight: '800' },
  clientSettingsGroup: { width: '100%', gap: 8 },
  clientSettingsGroupLabel: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.9, paddingHorizontal: 4 },
  clientSettingsList: { width: '100%', borderRadius: 22, padding: 6, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', ...cardShadow },
  clientSettingsRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#eef2f7' },
  clientSettingsRowIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#fff7ed', alignItems: 'center', justifyContent: 'center' },
  clientSettingsRowIconDanger: { backgroundColor: '#fee2e2' },
  clientSettingsRowLabel: { flex: 1, color: palette.ink, fontSize: 14, fontWeight: '600' },
  clientSettingsRowLabelDanger: { color: '#dc2626' },
  clientSettingsRowMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  clientSettingsRowValue: { color: palette.clayDeep, fontSize: 13, fontWeight: '700' },
  clientSettingsPanel: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 12, ...cardShadow },
  clientSettingsPanelTitle: { color: palette.ink, fontSize: 18, fontWeight: '800' },
  clientProfilePhotoEditor: { width: '100%', minHeight: 78, borderRadius: 18, padding: 12, backgroundColor: '#fff8f1', borderWidth: 1, borderColor: '#fed7aa', flexDirection: 'row', alignItems: 'center', gap: 12 },
  clientProfilePhotoPreview: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fdba74', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  clientProfilePhotoPreviewImage: { width: '100%', height: '100%' },
  clientProfilePhotoPreviewText: { color: palette.clayDeep, fontSize: 19, fontWeight: '800' },
  clientProfilePhotoEditorCopy: { flex: 1, minWidth: 0, gap: 3 },
  clientProfilePhotoEditorTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  clientProfilePhotoEditorText: { color: palette.body, fontSize: 12, lineHeight: 17 },
  clientProfilePhotoButton: { minHeight: 38, paddingHorizontal: 12, borderRadius: 12, backgroundColor: palette.clay, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  clientProfilePhotoButtonText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  clientSettingsPasswordNotice: { width: '100%', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 10, flexDirection: 'row', alignItems: 'flex-start', gap: 8, borderWidth: 1 },
  clientSettingsPasswordNoticeSuccess: { backgroundColor: '#eefbf4', borderColor: '#bbf7d0' },
  clientSettingsPasswordNoticeError: { backgroundColor: '#fff1f2', borderColor: '#fecdd3' },
  clientSettingsPasswordNoticeText: { flex: 1, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  clientSettingsPasswordNoticeTextSuccess: { color: '#15803d' },
  clientSettingsPasswordNoticeTextError: { color: '#dc2626' },
  clientSettingsInlinePanel: { width: '100%', borderRadius: 18, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e7edf3', gap: 10, ...cardShadow },
  clientSettingsInlineTitle: { color: palette.ink, fontSize: 15, fontWeight: '800' },
  clientSettingsInlineText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  clientSettingsChoiceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  clientSettingsChoice: { minHeight: 38, paddingHorizontal: 14, borderRadius: 12, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', alignItems: 'center', justifyContent: 'center' },
  clientSettingsChoiceActive: { backgroundColor: '#fff7ed', borderColor: '#fdba74' },
  clientSettingsChoiceText: { color: palette.body, fontSize: 12, fontWeight: '800' },
  clientSettingsChoiceTextActive: { color: palette.clayDeep },
  clientSettingsEmptyState: { width: '100%', borderRadius: 18, padding: 14, backgroundColor: '#fff8f1', borderWidth: 1, borderColor: '#fed7aa', gap: 6 },
  clientSettingsEmptyTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  clientSettingsEmptyText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  adminWorkspace: { width: '100%', maxWidth: 520, alignSelf: 'center', gap: 16 },
  adminDashboardTopBar: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  adminDashboardIconButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center', ...cardShadow },
  adminDashboardNotificationBadge: { position: 'absolute', top: 7, right: 7, minWidth: 18, height: 18, paddingHorizontal: 4, borderRadius: 9, backgroundColor: '#ef4444', alignItems: 'center', justifyContent: 'center' },
  adminDashboardNotificationBadgeText: { color: '#ffffff', fontSize: 9, fontWeight: '800' },
  adminDashboardIntro: { width: '100%', gap: 4 },
  adminDashboardTitle: { color: palette.ink, fontSize: 31, lineHeight: 35, fontWeight: '800' },
  adminDashboardSubtitle: { color: palette.body, fontSize: 14, lineHeight: 20 },
  adminOverviewCard: { width: '100%', borderRadius: 28, padding: 18, backgroundColor: palette.clay, borderWidth: 1, borderColor: '#f59b72', gap: 16, ...Platform.select({ web: { boxShadow: '0px 22px 38px rgba(201, 74, 34, 0.28)' }, default: { shadowColor: '#c94a22', shadowOpacity: 0.28, shadowRadius: 24, shadowOffset: { width: 0, height: 14 }, elevation: 8 } }) },
  adminOverviewHeader: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  adminOverviewEyebrow: { color: 'rgba(255,255,255,0.82)', fontSize: 12, fontWeight: '800' },
  adminOverviewDate: { color: '#ffffff', fontSize: 13, fontWeight: '600', marginTop: 2 },
  adminOverviewCalendar: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.18)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  adminOverviewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'space-between' },
  adminOverviewMetricCard: { flexGrow: 1, minHeight: 112, minWidth: 132, borderRadius: 18, padding: 14, backgroundColor: 'rgba(255,255,255,0.14)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', gap: 8 },
  adminOverviewMetricIcon: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  adminOverviewMetricValue: { color: '#ffffff', fontSize: 23, lineHeight: 27, fontWeight: '800' },
  adminOverviewMetricLabel: { color: 'rgba(255,255,255,0.84)', fontSize: 12, lineHeight: 17, fontWeight: '700' },
  adminSidebarOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'flex-start', zIndex: 30 },
  adminSidebarBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15, 23, 42, 0.18)' },
  adminSidebarSheet: { marginTop: 12, marginHorizontal: 18, borderRadius: 28, padding: 18, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', ...cardShadow },
  adminSidebarPage: { width: '100%', gap: 18 },
  adminSidebarIntro: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#eef2f7' },
  adminSidebarIntroCopy: { flex: 1, gap: 4 },
  adminSidebarIntroActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminSidebarTitle: { color: palette.ink, fontSize: 20, fontWeight: '800' },
  adminSidebarText: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminSidebarBadge: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#fff1eb', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#fed7aa' },
  adminSidebarBadgeText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  adminSidebarCloseButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#ffffff', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e5e7eb' },
  adminSidebarGroup: { width: '100%', gap: 10 },
  adminSidebarGroupLabel: { color: '#94a3b8', fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  adminSidebarList: { width: '100%', gap: 8 },
  adminSidebarItem: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 18, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', ...cardShadow },
  adminSidebarItemActive: { borderColor: '#fdba74', backgroundColor: '#fff7f3' },
  adminSidebarItemDanger: { borderColor: '#fecaca', backgroundColor: '#fffafa' },
  adminSidebarItemIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  adminSidebarItemCopy: { flex: 1, gap: 3 },
  adminSidebarItemTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  adminSidebarItemTitleDanger: { color: palette.danger },
  adminSidebarItemText: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminMoreMenuOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 24 },
  adminMoreMenuBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15, 23, 42, 0.08)' },
  adminMoreMenuCard: { position: 'absolute', alignSelf: 'center', borderRadius: 22, paddingHorizontal: 14, paddingTop: 10, paddingBottom: 12, backgroundColor: 'rgba(255,255,255,0.98)', borderWidth: 1, borderColor: '#e5e7eb', gap: 10, ...Platform.select({ web: { boxShadow: '0px 18px 34px rgba(15, 23, 42, 0.18)' }, default: { shadowColor: '#0f172a', shadowOpacity: 0.16, shadowRadius: 22, shadowOffset: { width: 0, height: 12 }, elevation: 8 } }) },
  adminMoreMenuHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 999, backgroundColor: '#d6d3d1' },
  adminMoreMenuList: { width: '100%', gap: 6 },
  adminMoreMenuItem: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 16, paddingHorizontal: 10, paddingVertical: 12, backgroundColor: '#ffffff' },
  adminMoreMenuItemIcon: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  adminMoreMenuItemCopy: { flex: 1, gap: 2 },
  adminMoreMenuItemTitle: { color: palette.ink, fontSize: 13, fontWeight: '800' },
  adminMoreMenuItemText: { color: palette.body, fontSize: 11, lineHeight: 16 },
  adminDashboardSection: { width: '100%', gap: 12 },
  adminDashboardSectionTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminQuickActionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'space-between' },
  adminQuickActionCard: { flexGrow: 1, minHeight: 116, minWidth: 132, borderRadius: 22, paddingHorizontal: 14, paddingVertical: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center', gap: 10, ...cardShadow },
  adminQuickActionIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  adminQuickActionLabel: { color: palette.ink, fontSize: 13, lineHeight: 18, fontWeight: '800', textAlign: 'center' },
  adminRecentHeader: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  adminRecentLink: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  adminRecentList: { width: '100%', borderRadius: 24, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', ...cardShadow },
  adminRecentItem: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#eef2f7' },
  adminRecentItemLast: { borderBottomWidth: 0 },
  adminRecentIconWrap: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center' },
  adminRecentCopy: { flex: 1, gap: 2 },
  adminRecentTitle: { color: palette.ink, fontSize: 13, lineHeight: 18, fontWeight: '800' },
  adminRecentMeta: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminRecentTime: { color: '#94a3b8', fontSize: 11, fontWeight: '700' },
  adminRecentEmptyState: { width: '100%', paddingVertical: 16, gap: 6 },
  adminRecentEmptyTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  adminRecentEmptyText: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminSectionHeaderCard: { width: '100%', borderRadius: 24, padding: 18, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 6, ...cardShadow },
  adminSectionHeaderTitle: { color: palette.ink, fontSize: 24, fontWeight: '800' },
  adminSectionHeaderText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  clientInfoBox: { width: '100%', borderRadius: 18, padding: 14, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', gap: 6 },
  clientInfoTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  clientInfoText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  clientAccountHeader: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  petDetailsScreen: { width: '100%', gap: 14 },
  petDetailsHero: { width: '100%', borderRadius: 28, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 14, ...cardShadow },
  petDetailsHeroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  petDetailsHeroActions: { flexDirection: 'row', gap: 10 },
  petDetailsIconButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center' },
  petDetailsHeroMedia: { minHeight: 250, borderRadius: 24, overflow: 'hidden', backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  petDetailsHeroImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  petDetailsHeroGlow: { position: 'absolute', width: 220, height: 220, borderRadius: 110, backgroundColor: 'rgba(255,255,255,0.12)' },
  petDetailsHeroIconWrap: { width: 132, height: 132, borderRadius: 66, backgroundColor: 'rgba(255,255,255,0.14)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center' },
  petDetailsHeroCopy: { gap: 6 },
  petDetailsHeroName: { color: palette.ink, fontSize: 34, lineHeight: 38, fontWeight: '800' },
  petDetailsHeroMeta: { color: palette.body, fontSize: 14, lineHeight: 20 },
  petDetailsFactRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  petDetailsFactCard: { flex: 1, minWidth: 98, borderRadius: 18, padding: 14, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e5e7eb', gap: 6 },
  petDetailsFactLabel: { color: palette.body, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8 },
  petDetailsFactValue: { color: palette.ink, fontSize: 15, fontWeight: '800' },
  petDetailsSection: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 10, ...cardShadow },
  petDetailsSectionTitle: { color: palette.ink, fontSize: 22, fontWeight: '800' },
  petDetailsBodyText: { color: palette.body, fontSize: 14, lineHeight: 24 },
  petDetailsList: { width: '100%', gap: 2 },
  petDetailsRow: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#eef2f7' },
  petDetailsRowLabel: { color: palette.body, fontSize: 14, fontWeight: '600' },
  petDetailsRowValue: { flexShrink: 1, color: palette.ink, fontSize: 14, fontWeight: '800', textAlign: 'right' },
  petDetailsRowValuePositive: { color: palette.success },
  petDetailsContactCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#f8fbff', borderWidth: 1, borderColor: '#dbeafe', gap: 12, ...cardShadow },
  petDetailsContactList: { gap: 10 },
  petDetailsContactItem: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, borderRadius: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb' },
  petDetailsContactIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#eaf2ff', alignItems: 'center', justifyContent: 'center' },
  petDetailsContactCopy: { flex: 1, gap: 2 },
  petDetailsContactLabel: { color: palette.body, fontSize: 12, fontWeight: '700' },
  petDetailsContactValue: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  petApplicationScreen: { width: '100%', gap: 14 },
  petApplicationHero: { width: '100%', borderRadius: 28, padding: 18, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', gap: 16, ...cardShadow },
  petApplicationHeroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  petApplicationBackButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center' },
  petApplicationHeroBadge: { minHeight: 36, paddingHorizontal: 14, borderRadius: 18, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center' },
  petApplicationHeroBadgeText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  petApplicationHeroBody: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 16 },
  petApplicationHeroMedia: { width: 112, height: 112, borderRadius: 28, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' },
  petApplicationHeroImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  petApplicationHeroGlow: { position: 'absolute', width: 94, height: 94, borderRadius: 47, backgroundColor: 'rgba(255,255,255,0.14)' },
  petApplicationHeroIconWrap: { width: 76, height: 76, borderRadius: 38, backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center' },
  petApplicationHeroCopy: { flex: 1, minWidth: 220, gap: 5 },
  petApplicationKicker: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  petApplicationTitle: { color: palette.ink, fontSize: 28, lineHeight: 34, fontWeight: '800' },
  petApplicationText: { color: palette.body, fontSize: 14, lineHeight: 22 },
  petApplicationFactRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  petApplicationFactCard: { flex: 1, minWidth: 110, borderRadius: 18, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fde3c2', gap: 5 },
  petApplicationFactLabel: { color: palette.clay, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  petApplicationFactValue: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  petApplicationLayout: { width: '100%', gap: 14 },
  petApplicationLayoutWide: { flexDirection: 'row', alignItems: 'flex-start' },
  petApplicationFormCard: { width: '100%', borderRadius: 24, padding: 18, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 12, ...cardShadow },
  petApplicationFormCardWide: { flex: 1.08 },
  petApplicationFormTitle: { color: palette.ink, fontSize: 24, fontWeight: '800' },
  petApplicationFormText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  petApplicationErrorText: { color: palette.danger, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  petApplicationSidePanel: { width: '100%', gap: 14 },
  petApplicationSidePanelWide: { flex: 0.84 },
  petApplicationInfoCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 8, ...cardShadow },
  petApplicationInfoTitle: { color: palette.ink, fontSize: 22, fontWeight: '800' },
  petApplicationInfoText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  petApplicationUploadCard: { width: '100%', borderRadius: 20, padding: 14, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e5e7eb', gap: 12 },
  petApplicationUploadCardError: { borderColor: palette.danger, backgroundColor: '#fff7f7' },
  petApplicationUploadHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  petApplicationUploadIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#fff7ed', alignItems: 'center', justifyContent: 'center' },
  petApplicationUploadCopy: { flex: 1, gap: 3 },
  petApplicationUploadTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  petApplicationUploadText: { color: palette.body, fontSize: 12, lineHeight: 18 },
  petApplicationUploadButton: { minHeight: 44, borderRadius: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center' },
  petApplicationUploadButtonText: { color: palette.clayDeep, fontSize: 13, fontWeight: '800' },
  petApplicationUploadList: { gap: 10 },
  petApplicationUploadItem: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, borderRadius: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb' },
  petApplicationUploadItemCopy: { flex: 1, gap: 2 },
  petApplicationUploadItemName: { color: palette.ink, fontSize: 13, fontWeight: '800' },
  petApplicationUploadItemMeta: { color: palette.body, fontSize: 11, lineHeight: 16 },
  petApplicationUploadRemove: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#fff7ed', alignItems: 'center', justifyContent: 'center' },
  petApplicationUploadEmpty: { color: palette.body, fontSize: 12, lineHeight: 18 },
  petApplicationChecklistCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e5e7eb', gap: 14, ...cardShadow },
  petApplicationChecklistItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  petApplicationChecklistBadge: { width: 28, height: 28, borderRadius: 14, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  petApplicationChecklistBadgeText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  petApplicationChecklistCopy: { flex: 1, gap: 3 },
  petApplicationChecklistTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  petApplicationChecklistText: { color: palette.body, fontSize: 12, lineHeight: 19 },
  petApplicationSuccessOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 1000, elevation: 1000, padding: 22, backgroundColor: 'rgba(15, 23, 42, 0.46)', alignItems: 'center', justifyContent: 'center' },
  petApplicationSuccessModal: { width: '100%', maxWidth: 360, borderRadius: 24, padding: 22, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#dcfce7', alignItems: 'center', gap: 12, ...cardShadow },
  petApplicationSuccessIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#16a34a', alignItems: 'center', justifyContent: 'center' },
  petApplicationSuccessTitle: { color: palette.ink, fontSize: 22, lineHeight: 27, fontWeight: '800', textAlign: 'center' },
  petApplicationSuccessText: { color: palette.body, fontSize: 13, lineHeight: 20, textAlign: 'center' },
  petApplicationSuccessButton: { width: '100%', minHeight: 46, borderRadius: 14, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', marginTop: 4 },
  petApplicationSuccessButtonText: { color: '#ffffff', fontSize: 14, fontWeight: '800' },
  clientHomeActivityPanel: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 12, ...cardShadow },
  clientHomeActivityHeader: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  clientHomeActivityText: { color: palette.body, fontSize: 13, lineHeight: 20, marginTop: 4 },
  clientHomeGhostButton: { minHeight: 40, paddingHorizontal: 14, borderRadius: 12, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#cbd5e1', alignItems: 'center', justifyContent: 'center' },
  clientHomeGhostButtonText: { color: palette.ink, fontSize: 12, fontWeight: '800' },
  clientHistoryRow: { width: '100%', borderRadius: 16, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  clientHistoryRowBody: { flex: 1, gap: 3 },
  hero: { width: '100%', borderRadius: 28, padding: 22, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 10, ...cardShadow },
  heroKicker: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.2 },
  heroTitle: { color: palette.ink, fontSize: 30, lineHeight: 36, fontWeight: '800' },
  heroText: { color: palette.body, fontSize: 15, lineHeight: 22 },
  roleRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 8 },
  sectionNav: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  notice: { width: '100%', borderRadius: 16, padding: 14, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa', flexDirection: 'row', gap: 10 },
  noticeText: { flex: 1, color: palette.clayDeep, fontWeight: '700' },
  card: { width: '100%', borderRadius: 24, padding: 18, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 10, ...cardShadow },
  cardKicker: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  cardTitle: { color: palette.ink, fontSize: 24, fontWeight: '800' },
  statusBadge: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, backgroundColor: '#fff7ed', borderWidth: 1, borderColor: '#fed7aa' },
  statusBadgeSuccess: { backgroundColor: '#f0fdf4', borderColor: '#bbf7d0' },
  statusBadgeDanger: { backgroundColor: '#fef2f2', borderColor: '#fecaca' },
  statusBadgeText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  statusBadgeTextSuccess: { color: '#44603f' },
  statusBadgeTextDanger: { color: palette.danger },
  redirectOptionList: { gap: 12 },
  redirectOption: { width: '100%', borderRadius: 18, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', gap: 6, ...cardShadow },
  redirectOptionTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  redirectOptionText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  sessionSummary: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  sessionChip: { minWidth: 120, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 12, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: palette.line },
  sessionChipLabel: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  sessionChipValue: { color: palette.ink, fontSize: 16, fontWeight: '800', marginTop: 4, textTransform: 'capitalize' },
  helper: { color: palette.body, fontSize: 13, lineHeight: 20 },
  field: { width: '100%', gap: 6 },
  fieldLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  fieldLabel: { color: palette.body, fontWeight: '700', fontSize: 13 },
  fieldLabelRequired: { color: palette.clayDeep, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  input: { minHeight: 46, borderRadius: 14, borderWidth: 1, borderColor: palette.lineStrong, backgroundColor: '#ffffff', paddingHorizontal: 14, paddingVertical: 12, color: palette.ink },
  inputError: { borderColor: palette.danger, backgroundColor: '#fff7f7' },
  inputMultiline: { minHeight: 86, textAlignVertical: 'top' },
  fieldErrorText: { color: palette.danger, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  primaryButton: { width: '100%', minHeight: 46, borderRadius: 14, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center' },
  primaryButtonDisabled: { backgroundColor: '#fdba74' },
  primaryButtonText: { color: palette.paper, fontWeight: '800' },
  primaryButtonTextDisabled: { color: '#fff7ed' },
  secondaryButton: { width: '100%', minHeight: 46, borderRadius: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#cbd5e1', alignItems: 'center', justifyContent: 'center' },
  secondaryButtonText: { color: palette.ink, fontWeight: '800' },
  dangerButton: { width: '100%', minHeight: 46, borderRadius: 14, backgroundColor: '#fef2f2', borderWidth: 1, borderColor: '#fecaca', alignItems: 'center', justifyContent: 'center' },
  dangerButtonText: { color: palette.danger, fontWeight: '800' },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  pill: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, borderWidth: 1, borderColor: palette.lineStrong, backgroundColor: '#ffffff' },
  pillCompact: { paddingVertical: 8 },
  pillActive: { backgroundColor: palette.clay, borderColor: palette.clay },
  pillDisabled: { opacity: 0.45 },
  pillText: { color: palette.body, fontWeight: '700', textTransform: 'capitalize' },
  pillTextActive: { color: palette.paper },
  adminAdoptionLayout: { width: '100%', gap: 16 },
  adminAdoptionLayoutSplit: { flexDirection: 'row', alignItems: 'flex-start' },
  adminAdoptionQueue: { flex: 1, gap: 14 },
  adminAdoptionQueueSplit: { flex: 1.02 },
  adminAdoptionQueueHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  adminAdoptionQueueCopy: { flex: 1, gap: 4 },
  adminAdoptionQueueTitle: { color: palette.ink, fontSize: 19, fontWeight: '800' },
  adminAdoptionQueueText: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminAdoptionQueueIcon: { width: 38, height: 38, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff1eb', borderWidth: 1, borderColor: '#fed7aa' },
  adminAdoptionFilterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  adminAdoptionFilterChip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0' },
  adminAdoptionFilterChipActive: { backgroundColor: '#fff1eb', borderColor: '#fdba74' },
  adminAdoptionFilterChipText: { color: palette.body, fontSize: 12, fontWeight: '800' },
  adminAdoptionFilterChipTextActive: { color: palette.clayDeep },
  adminAdoptionRequestList: { gap: 12 },
  adminAdoptionEmptyState: { width: '100%', borderRadius: 24, padding: 18, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#f3e8dd', gap: 6 },
  adminAdoptionEmptyTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminAdoptionEmptyText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  adminAdoptionRequestCard: { width: '100%', borderRadius: 24, padding: 16, backgroundColor: '#fffdfb', borderWidth: 1, borderColor: '#f1dfd3', gap: 14, ...cardShadow },
  adminAdoptionRequestCardActive: { borderColor: '#fb923c', backgroundColor: '#fff6f1' },
  adminAdoptionRequestHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  adminAdoptionApplicant: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  adminAdoptionAvatar: { width: 46, height: 46, borderRadius: 16, backgroundColor: '#fff1eb', alignItems: 'center', justifyContent: 'center' },
  adminAdoptionDetailAvatar: { width: 56, height: 56, borderRadius: 20, backgroundColor: '#fff1eb', alignItems: 'center', justifyContent: 'center' },
  adminAdoptionAvatarSuccess: { backgroundColor: '#eefbf4' },
  adminAdoptionAvatarDanger: { backgroundColor: '#fff1f2' },
  adminAdoptionAvatarText: { color: palette.clayDeep, fontSize: 15, fontWeight: '800' },
  adminAdoptionApplicantCopy: { flex: 1, gap: 4 },
  adminAdoptionApplicantName: { color: palette.ink, fontSize: 15, fontWeight: '800' },
  adminAdoptionApplicantMeta: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminAdoptionStatusPill: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, backgroundColor: '#fff3e8', borderWidth: 1, borderColor: '#fed7aa' },
  adminAdoptionStatusPillSuccess: { backgroundColor: '#eefbf4', borderColor: '#bbf7d0' },
  adminAdoptionStatusPillDanger: { backgroundColor: '#fff1f2', borderColor: '#fecdd3' },
  adminAdoptionStatusPillText: { color: palette.clayDeep, fontSize: 11, fontWeight: '800' },
  adminAdoptionStatusPillTextSuccess: { color: '#15803d' },
  adminAdoptionStatusPillTextDanger: { color: palette.danger },
  adminAdoptionRequestBody: { gap: 6 },
  adminAdoptionFieldLabel: { color: palette.clay, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  adminAdoptionFieldValue: { color: palette.ink, fontSize: 15, fontWeight: '700', lineHeight: 21 },
  adminAdoptionMessagePreview: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  adminAdoptionMessagePreviewText: { flex: 1, color: palette.body, fontSize: 13, lineHeight: 20 },
  adminAdoptionDetailCard: { width: '100%', borderRadius: 28, padding: 18, backgroundColor: '#fffaf6', borderWidth: 1, borderColor: '#f1dfd3', gap: 16, ...cardShadow },
  adminAdoptionDetailCardSplit: { flex: 0.98, minWidth: 320 },
  adminAdoptionDetailHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  adminAdoptionDetailIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  adminAdoptionDetailIdentityCopy: { flex: 1, gap: 4 },
  adminAdoptionDetailName: { color: palette.ink, fontSize: 20, fontWeight: '800' },
  adminAdoptionDetailMeta: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminAdoptionDetailInfoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  adminAdoptionInfoCard: { minWidth: 140, flexGrow: 1, borderRadius: 20, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#efe2d8', gap: 4 },
  adminAdoptionInfoTitle: { color: palette.ink, fontSize: 15, fontWeight: '800', lineHeight: 21 },
  adminAdoptionInfoText: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminAdoptionMessageCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#efe2d8', gap: 8 },
  adminAdoptionMessageCardText: { color: palette.body, fontSize: 14, lineHeight: 22 },
  adminAdoptionActionRow: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  adminAdoptionApproveButton: { flex: 1, minHeight: 48, minWidth: 150, borderRadius: 16, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  adminAdoptionApproveButtonText: { color: palette.paper, fontSize: 13, fontWeight: '800' },
  adminAdoptionRejectButton: { flex: 1, minHeight: 48, minWidth: 150, borderRadius: 16, backgroundColor: '#fff1f2', borderWidth: 1, borderColor: '#fecdd3', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  adminAdoptionRejectButtonText: { color: palette.danger, fontSize: 13, fontWeight: '800' },
  adminDonationLayout: { width: '100%', gap: 16 },
  adminDonationLayoutSplit: { flexDirection: 'row', alignItems: 'flex-start' },
  adminDonationQueue: { flex: 1, gap: 14 },
  adminDonationQueueSplit: { flex: 1.04 },
  adminDonationMetricGrid: { flexDirection: 'row', flexWrap: 'nowrap', gap: 10, alignItems: 'stretch', paddingRight: 2 },
  adminDonationMetricCard: { width: 180, flexGrow: 0, flexShrink: 0, borderRadius: 20, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', gap: 6, ...cardShadow },
  adminDonationMetricCardSplit: { width: 190 },
  adminDonationMetricIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  adminDonationMetricLabel: { color: '#94a3b8', fontSize: 11, fontWeight: '800' },
  adminDonationMetricValue: { color: palette.ink, fontSize: 24, fontWeight: '800' },
  adminDonationMetricNote: { color: palette.body, fontSize: 12, lineHeight: 17 },
  adminDonationSearchRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminDonationSearchShell: { flex: 1, minHeight: 48, borderRadius: 18, paddingHorizontal: 14, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminDonationSearchInput: { flex: 1, color: palette.ink, fontSize: 14, paddingVertical: 0 },
  adminDonationFilterIcon: { width: 48, height: 48, borderRadius: 18, backgroundColor: '#fff1eb', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center' },
  adminDonationTabRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  adminDonationTab: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 999, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e2e8f0' },
  adminDonationTabActive: { backgroundColor: '#fff1eb', borderColor: '#fdba74' },
  adminDonationTabText: { color: palette.body, fontSize: 12, fontWeight: '800' },
  adminDonationTabTextActive: { color: palette.clayDeep },
  adminDonationList: { gap: 12 },
  adminDonationEmptyState: { width: '100%', borderRadius: 22, padding: 18, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#f3e8dd', gap: 6 },
  adminDonationEmptyTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminDonationEmptyText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  adminDonationRow: { width: '100%', borderRadius: 22, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', flexDirection: 'row', alignItems: 'center', gap: 12, ...cardShadow },
  adminDonationRowActive: { borderColor: '#fdba74', backgroundColor: '#fff7f3' },
  adminDonationAvatar: { width: 44, height: 44, borderRadius: 18, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  adminDonationDetailAvatar: { width: 56, height: 56, borderRadius: 20, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  adminDonationAvatarText: { fontSize: 15, fontWeight: '800' },
  adminDonationRowCopy: { flex: 1, gap: 4 },
  adminDonationRowName: { color: palette.ink, fontSize: 15, fontWeight: '800' },
  adminDonationRowMeta: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminDonationAmountBlock: { minWidth: 88, alignItems: 'flex-end', gap: 3 },
  adminDonationAmountValue: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminDonationMethodText: { color: palette.body, fontSize: 11, fontWeight: '700' },
  adminDonationStatusPill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, backgroundColor: '#eff6ff', borderWidth: 1, borderColor: '#bfdbfe' },
  adminDonationStatusPillSuccess: { backgroundColor: '#eefbf4', borderColor: '#bbf7d0' },
  adminDonationStatusPillWarning: { backgroundColor: '#fff7ed', borderColor: '#fed7aa' },
  adminDonationStatusPillDanger: { backgroundColor: '#fff1f2', borderColor: '#fecdd3' },
  adminDonationStatusPillText: { color: palette.sky, fontSize: 10, fontWeight: '800' },
  adminDonationStatusPillTextSuccess: { color: '#15803d' },
  adminDonationStatusPillTextWarning: { color: palette.warning },
  adminDonationStatusPillTextDanger: { color: palette.danger },
  adminDonationManualButton: { width: '100%', minHeight: 50, borderRadius: 16, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, paddingHorizontal: 16 },
  adminDonationManualButtonText: { color: palette.paper, fontSize: 14, fontWeight: '800' },
  adminDonationDetailCard: { width: '100%', borderRadius: 28, padding: 18, backgroundColor: '#fffaf6', borderWidth: 1, borderColor: '#f1dfd3', gap: 16, ...cardShadow },
  adminDonationDetailCardSplit: { flex: 0.96, minWidth: 320 },
  adminDonationDetailHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  adminDonationDetailIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  adminDonationDetailIdentityCopy: { flex: 1, gap: 4 },
  adminDonationDetailName: { color: palette.ink, fontSize: 20, fontWeight: '800' },
  adminDonationDetailMeta: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminDonationDetailInfoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  adminDonationInfoCard: { minWidth: 140, flexGrow: 1, borderRadius: 20, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#efe2d8', gap: 4 },
  adminDonationInfoLabel: { color: palette.clay, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  adminDonationInfoValue: { color: palette.ink, fontSize: 15, fontWeight: '800', lineHeight: 21 },
  adminDonationInfoText: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminDonationNoteCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#efe2d8', gap: 8 },
  adminDonationNoteText: { color: palette.body, fontSize: 14, lineHeight: 22 },
  adminDonationDetailActions: { width: '100%', gap: 10 },
  adminDonationDeleteButton: { width: '100%', minHeight: 48, borderRadius: 16, backgroundColor: '#fff1f2', borderWidth: 1, borderColor: '#fecdd3', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  adminDonationDeleteButtonText: { color: palette.danger, fontSize: 13, fontWeight: '800' },
  adminDonationDetailsPage: { width: '100%', gap: 16 },
  adminDonationBackButton: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 2, paddingVertical: 4 },
  adminDonationBackButtonText: { color: palette.ink, fontSize: 13, fontWeight: '700' },
  adminDonationDetailsHero: { width: '100%', borderRadius: 24, padding: 18, backgroundColor: palette.clay, gap: 16, ...cardShadow },
  adminDonationDetailsHeroHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  adminDonationDetailsHeroIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  adminDonationDetailsHeroAvatar: { width: 56, height: 56, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  adminDonationDetailsHeroAvatarText: { color: palette.paper, fontSize: 18, fontWeight: '800' },
  adminDonationDetailsHeroCopy: { flex: 1, gap: 4 },
  adminDonationDetailsHeroName: { color: palette.paper, fontSize: 20, fontWeight: '800' },
  adminDonationDetailsHeroEmail: { color: '#fff7ed', fontSize: 13, lineHeight: 18 },
  adminDonationDetailsHeroMeta: { color: '#ffedd5', fontSize: 12, lineHeight: 17 },
  adminDonationDetailsHeroStatus: { backgroundColor: '#eefbf4', borderColor: '#bbf7d0' },
  adminDonationDetailsHeroStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  adminDonationDetailsHeroStat: { flex: 1, minWidth: 160, gap: 5 },
  adminDonationDetailsHeroStatLabel: { color: '#ffedd5', fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  adminDonationDetailsHeroStatValue: { color: palette.paper, fontSize: 28, fontWeight: '800' },
  adminDonationDetailsHeroStatValueSmall: { color: palette.paper, fontSize: 16, fontWeight: '800' },
  adminDonationDetailsSection: { width: '100%', gap: 10 },
  adminDonationDetailsSectionTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminDonationDetailsInfoList: { width: '100%', borderRadius: 22, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', gap: 12, ...cardShadow },
  adminDonationDetailsInfoRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  adminDonationDetailsInfoLabelWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  adminDonationDetailsInfoLabel: { color: palette.body, fontSize: 13, fontWeight: '700' },
  adminDonationDetailsInfoValue: { flexShrink: 1, color: palette.ink, fontSize: 13, lineHeight: 18, fontWeight: '700', textAlign: 'right' },
  adminDonationDetailsReceiptLink: { color: palette.clayDeep, fontSize: 13, fontWeight: '800' },
  adminDonationDetailsMessageCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', flexDirection: 'row', alignItems: 'flex-start', gap: 12, ...cardShadow },
  adminDonationDetailsMessageBubble: { width: 34, height: 34, borderRadius: 12, backgroundColor: '#fff1eb', alignItems: 'center', justifyContent: 'center' },
  adminDonationDetailsMessageBubbleText: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  adminDonationDetailsMessageText: { flex: 1, color: palette.body, fontSize: 13, lineHeight: 20 },
  adminDonationDetailsBreakdownCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', gap: 12, ...cardShadow },
  adminDonationDetailsBreakdownRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  adminDonationDetailsBreakdownLabel: { color: palette.body, fontSize: 13, fontWeight: '700' },
  adminDonationDetailsBreakdownValue: { color: palette.ink, fontSize: 13, fontWeight: '700' },
  adminDonationDetailsBreakdownNetLabel: { color: '#15803d', fontSize: 13, fontWeight: '800' },
  adminDonationDetailsBreakdownNetValue: { color: '#15803d', fontSize: 14, fontWeight: '800' },
  adminDonationDetailsActionRow: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  adminDonationDetailsSecondaryButton: { flex: 1, minWidth: 160, minHeight: 48, borderRadius: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fdba74', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, paddingHorizontal: 16 },
  adminDonationDetailsSecondaryButtonText: { color: palette.clayDeep, fontSize: 13, fontWeight: '800' },
  adminDonationDetailsPrimaryButton: { flex: 1, minWidth: 160, minHeight: 48, borderRadius: 16, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, paddingHorizontal: 16 },
  adminDonationDetailsPrimaryButtonText: { color: palette.paper, fontSize: 13, fontWeight: '800' },
  adminHealthLayout: { width: '100%', gap: 16 },
  adminHealthMetricGrid: { flexDirection: 'row', flexWrap: 'nowrap', gap: 10, alignItems: 'stretch', paddingRight: 2 },
  adminHealthMetricCard: { width: 180, flexGrow: 0, flexShrink: 0, borderRadius: 20, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', gap: 6, ...cardShadow },
  adminHealthMetricCardSplit: { width: 190 },
  adminHealthMetricIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  adminHealthMetricLabel: { color: '#94a3b8', fontSize: 11, fontWeight: '800' },
  adminHealthMetricValue: { color: palette.ink, fontSize: 24, fontWeight: '800' },
  adminHealthMetricNote: { color: palette.body, fontSize: 12, lineHeight: 17 },
  adminHealthSearchRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminHealthSearchShell: { flex: 1, minHeight: 48, borderRadius: 18, paddingHorizontal: 14, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminHealthSearchInput: { flex: 1, color: palette.ink, fontSize: 14, paddingVertical: 0 },
  adminHealthFilterIcon: { width: 48, height: 48, borderRadius: 18, backgroundColor: '#fff1eb', borderWidth: 1, borderColor: '#fed7aa', alignItems: 'center', justifyContent: 'center' },
  adminHealthTabRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  adminHealthTab: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 999, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e2e8f0' },
  adminHealthTabActive: { backgroundColor: '#fff1eb', borderColor: '#fdba74' },
  adminHealthTabText: { color: palette.body, fontSize: 12, fontWeight: '800' },
  adminHealthTabTextActive: { color: palette.clayDeep },
  adminHealthContent: { width: '100%', gap: 14 },
  adminHealthContentSplit: { flexDirection: 'row', alignItems: 'flex-start' },
  adminHealthQueue: { flex: 1, gap: 12 },
  adminHealthQueueSplit: { flex: 0.92 },
  adminHealthEmptyState: { width: '100%', borderRadius: 22, padding: 18, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#f3e8dd', gap: 6 },
  adminHealthEmptyTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminHealthEmptyText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  adminHealthRow: { width: '100%', borderRadius: 22, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', flexDirection: 'row', alignItems: 'center', gap: 12, ...cardShadow },
  adminHealthRowActive: { borderColor: '#fdba74', backgroundColor: '#fff7f3' },
  adminHealthAvatar: { width: 48, height: 48, borderRadius: 18, backgroundColor: '#fff1eb', alignItems: 'center', justifyContent: 'center' },
  adminHealthDetailAvatar: { width: 58, height: 58, borderRadius: 20, backgroundColor: '#fff1eb', alignItems: 'center', justifyContent: 'center' },
  adminHealthAvatarDanger: { backgroundColor: '#fff1f2' },
  adminHealthAvatarWarning: { backgroundColor: '#fff7ed' },
  adminHealthAvatarSuccess: { backgroundColor: '#eefbf4' },
  adminHealthAvatarText: { color: palette.clayDeep, fontSize: 15, fontWeight: '800' },
  adminHealthRowCopy: { flex: 1, gap: 3 },
  adminHealthRowName: { color: palette.ink, fontSize: 15, fontWeight: '800' },
  adminHealthRowMeta: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminHealthRowSummary: { color: palette.ink, fontSize: 13, lineHeight: 19, fontWeight: '700' },
  adminHealthRowStatusBlock: { alignItems: 'flex-end', gap: 6 },
  adminHealthStatusPill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, backgroundColor: '#fff1eb', borderWidth: 1, borderColor: '#fed7aa' },
  adminHealthStatusPillDanger: { backgroundColor: '#fff1f2', borderColor: '#fecdd3' },
  adminHealthStatusPillWarning: { backgroundColor: '#fff7ed', borderColor: '#fed7aa' },
  adminHealthStatusPillSuccess: { backgroundColor: '#eefbf4', borderColor: '#bbf7d0' },
  adminHealthStatusPillText: { color: palette.clayDeep, fontSize: 10, fontWeight: '800' },
  adminHealthStatusPillTextDanger: { color: palette.danger },
  adminHealthStatusPillTextWarning: { color: palette.warning },
  adminHealthStatusPillTextSuccess: { color: '#15803d' },
  adminHealthDetailCard: { width: '100%', borderRadius: 28, padding: 18, backgroundColor: '#fffaf6', borderWidth: 1, borderColor: '#f1dfd3', gap: 16, ...cardShadow },
  adminHealthDetailCardSplit: { flex: 1.08, minWidth: 340 },
  adminHealthDetailHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  adminHealthDetailIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  adminHealthDetailIdentityCopy: { flex: 1, gap: 4 },
  adminHealthDetailName: { color: palette.ink, fontSize: 20, fontWeight: '800' },
  adminHealthDetailMeta: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminHealthDetailInfoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  adminHealthInfoCard: { minWidth: 140, flexGrow: 1, borderRadius: 20, padding: 14, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#efe2d8', gap: 4 },
  adminHealthInfoLabel: { color: palette.clay, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  adminHealthInfoValue: { color: palette.ink, fontSize: 15, fontWeight: '800', lineHeight: 21 },
  adminHealthInfoText: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminHealthWorkspaceGrid: { width: '100%', gap: 12 },
  adminHealthWorkspaceCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', gap: 10, ...cardShadow },
  adminHealthWorkspaceTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminHealthWorkspaceText: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminHealthMiniCard: { width: '100%', borderRadius: 16, padding: 12, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#f3e8dd', gap: 6 },
  adminHealthMiniCardTitle: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  adminHealthMiniCardText: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminHealthRecordPage: { width: '100%', gap: 16 },
  adminHealthRecordBackButton: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 2, paddingVertical: 4 },
  adminHealthRecordBackButtonText: { color: palette.ink, fontSize: 13, fontWeight: '700' },
  adminHealthRecordHero: { width: '100%', borderRadius: 24, padding: 18, backgroundColor: '#fff7f3', borderWidth: 1, borderColor: '#fed7aa', gap: 14, ...cardShadow },
  adminHealthRecordHeroHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  adminHealthRecordHeroIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  adminHealthRecordHeroAvatar: { width: 62, height: 62, borderRadius: 22, backgroundColor: '#fff1eb', alignItems: 'center', justifyContent: 'center' },
  adminHealthRecordHeroAvatarText: { color: palette.clayDeep, fontSize: 18, fontWeight: '800' },
  adminHealthRecordHeroCopy: { flex: 1, gap: 4 },
  adminHealthRecordHeroName: { color: palette.ink, fontSize: 22, fontWeight: '800' },
  adminHealthRecordHeroMeta: { color: palette.body, fontSize: 13, lineHeight: 19 },
  adminHealthRecordHeroSubtext: { color: palette.clayDeep, fontSize: 12, fontWeight: '800' },
  adminHealthRecordTabRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  adminHealthRecordTab: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e2e8f0' },
  adminHealthRecordTabActive: { backgroundColor: '#fff1eb', borderColor: '#fdba74' },
  adminHealthRecordTabText: { color: palette.body, fontSize: 12, fontWeight: '800' },
  adminHealthRecordTabTextActive: { color: palette.clayDeep },
  adminHealthRecordSectionCard: { width: '100%', borderRadius: 22, padding: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#ece7e2', gap: 10, ...cardShadow },
  adminHealthRecordSectionTitle: { color: palette.ink, fontSize: 16, fontWeight: '800' },
  adminHealthRecordMetricList: { gap: 10 },
  adminHealthRecordMetricRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  adminHealthRecordMetricLabel: { color: palette.body, fontSize: 13, fontWeight: '700' },
  adminHealthRecordMetricValue: { color: palette.ink, fontSize: 13, fontWeight: '800', textAlign: 'right', flexShrink: 1 },
  adminHealthRecordMetricValueDanger: { color: palette.danger },
  adminHealthRecordMetricValueWarning: { color: palette.warning },
  adminHealthRecordMetricValueSuccess: { color: '#15803d' },
  adminHealthRecordDiagnosisTitle: { color: palette.ink, fontSize: 15, fontWeight: '800', lineHeight: 21 },
  adminHealthRecordDiagnosisMeta: { color: palette.body, fontSize: 12, lineHeight: 18 },
  adminHealthRecordBodyText: { color: palette.body, fontSize: 13, lineHeight: 20 },
  adminHealthRecordActionRow: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  adminHealthRecordSecondaryButton: { flex: 1, minWidth: 160, minHeight: 48, borderRadius: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fdba74', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, paddingHorizontal: 16 },
  adminHealthRecordSecondaryButtonText: { color: palette.clayDeep, fontSize: 13, fontWeight: '800' },
  adminHealthRecordPrimaryButton: { flex: 1, minWidth: 160, minHeight: 48, borderRadius: 16, backgroundColor: palette.clay, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, paddingHorizontal: 16 },
  adminHealthRecordPrimaryButtonText: { color: palette.paper, fontSize: 13, fontWeight: '800' },
  record: { width: 150, marginRight: 10, borderRadius: 18, padding: 12, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#ead7c6', gap: 6 },
  recordActive: { borderColor: '#fb923c', backgroundColor: '#fff1eb' },
  recordTitle: { color: palette.ink, fontWeight: '800' },
  recordMeta: { color: palette.body, fontSize: 12 },
  panel: { width: '100%', borderRadius: 20, padding: 16, backgroundColor: '#fffdfb', borderWidth: 1, borderColor: '#ead7c6', gap: 10, ...cardShadow },
  panelTitle: { color: palette.ink, fontSize: 18, fontWeight: '800' },
  rowCard: { width: '100%', borderRadius: 16, padding: 12, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#ead7c6', gap: 4 },
  toggleRow: { width: '100%', minHeight: 46, borderRadius: 16, paddingHorizontal: 14, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#ead7c6', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  metricCard: { borderRadius: 18, padding: 14, backgroundColor: '#fff8f1', borderWidth: 1, borderColor: '#fde3c2', ...cardShadow },
  metricLabel: { color: palette.clay, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  metricValue: { color: palette.ink, fontSize: 24, fontWeight: '800', marginTop: 6 },
  divider: { height: 1, backgroundColor: palette.line, marginVertical: 4 },
});

